[package]
name = "nmea"
version = "0.4.0"

authors = [
  "Felix Obenhuber <felix@obenhuber.de>",
  "Evgeniy A. Dushistov <dushistov@mail.ru>",
  "Henrik Böving <hargonix@gmail.com>",
  "Lachezar Lechev <elpiel93@gmail.com>",
  "AeroRust <aerospace.rust@gmail.com>",
]

categories = ["parser-implementations", "no-std", "embedded"]
keywords = ["NMEA", "gps", "glonass", "coordinate", "position"]
description = "Simple NMEA 0183 parser"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/nmea"
repository = "https://github.com/AeroRust/nmea"
readme = "README.md"

edition = "2021"
rust-version = "1.60"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
arrayvec = { version = "0.7.2", default-features = false, features = ["serde"]}
chrono = { version = "0.4.19", default-features = false, features = ["serde"] }
heapless = { version ="0.7.15", features = ["serde"]}
nom = { version = "7.1.1", default-features = false }

# we include num-traits only when `std` is not enabled
# because of `fract()` and `trunc()` methods
num-traits = { version = "0.2", default-features = false }
serde = { version = "1.0.163", features = ["derive"], default-features = false }
serde_with = { version = "3.0.0", default-features = false, features = ["macros", "chrono"] }

[dev-dependencies]
approx = "0.5.1"
doc-comment = "0.3"
pretty_assertions = "1"
quickcheck = { version = "1.0.3", default-features = false }
criterion = "0.4"

[features]
default = ["std"]
std = ["nom/std", "chrono/std", "arrayvec/std"]

[[bench]]
name = "nom_parsing"
harness = false

[[bench]]
name = "gsv_parser"
harness = false
